
CREATE TABLE CLIENTE(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(60),
APELLIDOS VARCHAR(120),
FECHA_NACIMIENTO DATE,
SEXO VARCHAR(1)
);

CREATE TABLE CUENTA(
ID_CUENTA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT,
SALDO DOUBLE,
TIPO_PRODUCTO VARCHAR(120)
);


CREATE TABLE PROPERTIES(
APPLICATION VARCHAR(100),
PROFILE VARCHAR(14),
LABEL VARCHAR(100),
KEY VARCHAR(200),
VALUE VARCHAR(350)
);